site_name: Developer Documentation

copyright: "&copy; 2015 - <script>document.write(new Date().getFullYear())</script> <a href='https://www.caktusgroup.com' target='_blank'>Caktus Group</a>"

theme:
  # Main site theme
  name: material
  logo: assets/logo.svg
  features:
    - navigation.tabs
    # Avoids the navbar from collapsing when scrolling down
    - navigation.tabs
    - navigation.tabs.sticky
  # Enables dark-mode
  palette:
    - media: "(prefers-color-scheme: light)" # 
      scheme: default
      # Customize primary color
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  # Social media links 
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/caktus-consulting-group-llc/
    - icon: fontawesome/brands/github
      link: https://github.com/caktus
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/caktusgroup
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/CaktusGroup/
  # Google analytics - uses Universal Analytics
  analytics:
    provider: google
    property: UA-15492387-4
    # Collects user feedback at bottom of page
    feedback:
      title: Was the content helpful?
      ratings:
        - icon: material/heart
          name: Helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: Could be improved
          data: 0
          note: >- 
            Thanks for your feedback!

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details

plugins:
  - git-revision-date
  - search

repo_url: https://github.com/caktus/developer-documentation
repo_name: developer-documentation
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/extra.css
