name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache virtual environment
        uses: actions/cache@v2
        id: cache-venv
        with:
          # What we cache: the virtualenv
          path: venv/
          # The cache key depends on: requirements.txt
          key: ${{ runner.os }}-venv-v1-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-v1-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv/
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: |
          source venv/bin/activate
          mkdocs gh-deploy --force
